version: '3.5'

services:
  nx-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    container_name: nx-api
    environment:
      NODE_ENV: docker
    working_dir: /code
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      - nx-mysql
    ports:
      - 8080:80
      - 9080:9000

  nx-mysql:
    image: mysql:5.7
    container_name: nx-mysql
    command: --max_allowed_packet=32505856
    volumes:
       - ./docker/mysql:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: application
    ports:
       - 3392:3306
